del /f /q *.prt
del /f /q *.pln
del /f /q *.p0
del /f /q *.p1
del /f /q *.p2
del /f /q *.p3
del /f /q *.b0
del /f /q *.b1
del /f /q *.b2
del /f /q *.b3
del /f /q *.log
del /f /q *.hsz
del /f /q *.err
del /f /q *.lin
del /f /q *.pts
del /f /q *.ext
del /f /q *.wic
del /f /q *.ent
del /f /q *.wa_
del /f /q *.dlit
del /f /q *.nrp